// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

console.log(process.env["DATABASE_URL"], "this is in the config file");

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
		seed: "bun run prisma/seed.ts",
	},
	datasource: {
		url: process.env["DATABASE_URL"],
	},
});
